import mysql.connector

mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  passwd="root",
  database="algo_trade"
)




stocks_to_scan ={'AUBANK','ADANIPORTS','ADANIPOWER','ABCAPITAL','ABFRL','AJANTPHARM','ALKEM','ALBK','AMARAJABAT','AMBUJACEM','APOLLOHOSP','APOLLOTYRE','ASHOKLEY','ASIANPAINT','AUROPHARMA','DMART','AXISBANK','BAJAJ-AUTO','BAJFINANCE','BAJAJFINSV','BAJAJHLDNG','BALKRISIND','BANDHANBNK','BANKBARODA','BANKINDIA','BATAINDIA','BERGEPAINT','BEL','BHARATFORG','BHEL','BPCL','BHARTIARTL','INFRATEL','BIOCON','BBTC','BOSCHLTD','BRITANNIA','CESC','CADILAHC','CANBK','CASTROLIND','CHOLAFIN','CIPLA','CUB','COALINDIA','COLPAL','CONCOR','COROMANDEL','CROMPTON','CUMMINSIND','DLF','DABUR','DALBHARAT','DIVISLAB','DRREDDY','EDELWEISS','EICHERMOT','EMAMILTD','ENDURANCE','ENGINERSIN','ESCORTS','EXIDEIND','FEDERALBNK','FCONSUMER','FRETAIL','GAIL','GMRINFRA','GICRE','GLENMARK','GODREJAGRO','GODREJCP','GODREJIND','GODREJPROP','GRAPHITE','GRASIM','GSPL','HEG','HCLTECH','HDFCAMC','HDFCBANK','HDFCLIFE','HAVELLS','HEROMOTOCO','HEXAWARE','HINDALCO','HINDPETRO','HINDUNILVR','HINDZINC','HUDCO','HDFC','ICICIBANK','ICICIGI','ICICIPRULI','IDBI','IDFCFIRSTB','ITC','IBULHSGFIN','IBVENTURES','INDIANB','INDHOTEL','IOC','IGL','INDUSINDBK','NAUKRI','INFY','INDIGO','IPCALAB','JSWENERGY','JSWSTEEL','JINDALSTEL','JUBLFOOD','JUBILANT','KOTAKBANK','L&TFH','LTTS','LICHSGFIN','LTI','LT','LUPIN','MRF','MGL','M&MFIN','M&M','MANAPPURAM','MRPL','MARICO','MARUTI','MFSL','MINDTREE','MOTHERSUMI','MPHASIS','MUTHOOTFIN','NATCOPHARM','NBCC','NHPC','NMDC','NTPC','NATIONALUM','NESTLEIND','OBEROIRLTY','ONGC','OIL','OFSS','ORIENTBANK','PIIND','PNBHOUSING','PAGEIND','PETRONET','PFIZER','PIDILITIND','PEL','PFC','POWERGRID','PRESTIGE','PGHH','PNB','QUESS','RBLBANK','RECLTD','RAJESHEXPO','RELIANCE','RNAM','SBILIFE','SRF','SHREECEM','SRTRANSFIN','SIEMENS','SBIN','SAIL','STRTECH','SUNPHARMA','SUNTV','SYNGENE','TVSMOTOR','TATACHEM','TCS','TATAGLOBAL','TATAMTRDVR','TATAMOTORS','TATAPOWER','TATASTEEL','TECHM','NIACL','RAMCOCEM','TITAN','TORNTPHARM','TORNTPOWER','UPL','ULTRACEMCO','UNIONBANK','UBL','MCDOWELL-N','VGUARD','VARROC','VEDL','IDEA','VOLTAS','WIPRO','YESBANK','ZEEL'} 

stocks_to_scan1 ={'ACC'}